# Generated by Django 6.0.4 on 2026-04-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_categoria_produto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='descricaao',
        ),
    ]
